version: '3.9'
name: khazir-mart

services:
  user:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    container_name: khazir-mart-user
    volumes:
      - ./user-service:/code
    depends_on:
      - database
    ports:
      - "8081:8081"  
    networks:
      - mart-network
#======================================================================================
  inventory:
    build: 
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: khazir-mart-inventory
    volumes:
      - ./inventory-service:/code
    depends_on:
      - database
    ports:
      - "8002:8002"
    networks:
      - mart-network

#=======================================================================================      
  database:
    image: postgres:16
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=abdurrehman                     
      - POSTGRES_PASSWORD=your_password               
      - POSTGRES_DB=mydatabase
    ports:
      - '5433:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - mart-network
#=======================================================================================
volumes:
  postgres_db:
    driver: local
    
networks:
  mart-network:
    driver: bridge
